# Generated by Django 3.1 on 2020-09-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20200922_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=models.FileField(upload_to=''),
        ),
    ]
