# Generated by Django 3.1 on 2020-09-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20200922_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='information',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=models.FileField(upload_to='static/images/img'),
        ),
    ]
